{% set name = "symforce" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/symforce-org/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3205c37f1358b93d4fe9274789647729d376f9763f1d40923f57811ae894b525 

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - pip

  host:
    - eigen >=3.3
    - fmt >=8.0,<9.0
    - spdlog >=1.9,<=1.10
    - tl-optional
    - argh

  run: 
    - eigen >=3.3
    - fmt >=8.0,<9.0
    - spdlog >=1.9,<=1.10
    - tl-optional
    - numpy
    - sympy

test:
  commands:
    - test -f ${PREFIX}/include/symforce/opt/key.h  # [unix]

about:
  home: https://github.com/symforce-org/symforce
  summary: 'Fast symbolic computation, code generation, and nonlinear optimization for robotics'
  description: |
    SymForce is a fast symbolic computation and code generation library for robotics applications like computer vision, state estimation, motion planning, and controls. It combines the development speed and flexibility of symbolic mathematics with the performance of autogenerated, highly optimized code in C++ or any target runtime language.
  license: Apache v2
  license_family: Apache
  license_file: LICENSE
  doc_url: https://symforce.org/
  dev_url: https://github.com/symforce-org/symforce

extra:
  recipe-maintainers:
    - chao-qu-skydio
    - aaron-skydio
    - hayk-skydio
